version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - pip install -U pip
      - pip install -r requirements.txt

sphinx:
  configuration: docs/conf.py
  builder: html #Puede ser también pdf
  fail_on_warning: false