version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"  # Let Read the Docs handle Python version
  jobs:
    post_checkout:
      - echo "Configurando version de python."
      - python --version

install:
  requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false